"""
Reads signed provenance.

The detectors are pure functions over the parsed manifest JSON, so they are driven here
with hand-written stores rather than signed assets: no certificate, no key, and each
test states exactly which field it is about. The reader itself is exercised separately
against real bytes, where the only thing that matters is that it never raises.
"""

from __future__ import annotations

from guard_local.sources.c2pa import (
    contains_generative_ai_marker,
    detect_ai_generation,
    get_actions,
    get_manifest_chain,
    get_software_agent_name,
    is_ai_digital_source_type,
    matches_known_ai_vendor,
    read_manifest_chain,
)
from guard_local.sources.c2pa.detectors import (
    detect_ai_action_description,
    detect_ai_claim_generator,
    detect_ai_digital_source_type,
    detect_ai_generated_action,
    detect_ai_software_agent,
    detect_generative_ai_metadata_marker,
    detect_generative_info_assertion,
    detect_training_or_mining_assertion,
)

from .conftest import jpeg_bytes, manifest, manifest_store, png_bytes

TRAINED_ALGORITHMIC = (
    "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
)


class TestManifestChain:
    def test_the_active_manifest_comes_first(self) -> None:
        store = manifest_store(
            "urn:a",
            **{
                "urn:a": manifest("urn:a", ingredients=[{"active_manifest": "urn:b"}]),
                "urn:b": manifest("urn:b"),
            },
        )

        assert [m["label"] for m in get_manifest_chain(store)] == ["urn:a", "urn:b"]

    def test_ingredients_are_followed_to_the_bottom(self) -> None:
        """
        Ensure the whole ancestry is walked.

        The strongest evidence sits at the moment of creation, in the earliest
        ingredient. An image generated by a model and then merely cropped records the
        generation there, while its active manifest says only that it was cropped.
        """
        store = manifest_store(
            "urn:a",
            **{
                "urn:a": manifest("urn:a", ingredients=[{"active_manifest": "urn:b"}]),
                "urn:b": manifest("urn:b", ingredients=[{"active_manifest": "urn:c"}]),
                "urn:c": manifest("urn:c"),
            },
        )

        assert len(get_manifest_chain(store)) == 3

    def test_a_cycle_does_not_hang(self) -> None:
        store = manifest_store(
            "urn:a",
            **{
                "urn:a": manifest("urn:a", ingredients=[{"active_manifest": "urn:b"}]),
                "urn:b": manifest("urn:b", ingredients=[{"active_manifest": "urn:a"}]),
            },
        )

        assert len(get_manifest_chain(store)) == 2

    def test_an_ingredient_pointing_nowhere_is_skipped(self) -> None:
        store = manifest_store(
            "urn:a",
            **{
                "urn:a": manifest(
                    "urn:a", ingredients=[{"active_manifest": "urn:gone"}]
                )
            },
        )

        assert len(get_manifest_chain(store)) == 1

    def test_an_empty_or_missing_store_yields_nothing(self) -> None:
        assert get_manifest_chain(None) == []
        assert get_manifest_chain({}) == []
        assert get_manifest_chain({"active_manifest": "urn:a", "manifests": {}}) == []


class TestActions:
    def test_versioned_action_assertions_are_accepted(self) -> None:
        """`c2pa.actions.v2` is what current writers emit; `c2pa.actions` is older."""
        for label in ("c2pa.actions", "c2pa.actions.v2"):
            found = get_actions(
                {
                    "assertions": [
                        {"label": label, "data": {"actions": [{"action": "x"}]}}
                    ]
                }
            )
            assert len(found) == 1

    def test_other_assertions_are_ignored(self) -> None:
        found = get_actions(
            {"assertions": [{"label": "stds.schema-org.CreativeWork", "data": {}}]}
        )

        assert found == []

    def test_a_manifest_with_no_assertions_is_fine(self) -> None:
        assert get_actions({}) == []
        assert get_actions({"assertions": None}) == []

    def test_a_software_agent_may_be_a_string_or_a_structure(self) -> None:
        assert get_software_agent_name("Firefly") == "Firefly"
        assert get_software_agent_name({"name": "Firefly", "version": "1"}) == "Firefly"
        assert get_software_agent_name(None) is None


class TestVendorAndSourceMatching:
    def test_a_vendor_is_found_inside_a_longer_string(self) -> None:
        """Agents identify themselves as `Product/1.0`, not as a bare name."""
        assert matches_known_ai_vendor("Adobe Firefly/2.1 (macOS)") == "firefly"

    def test_matching_is_case_insensitive(self) -> None:
        assert matches_known_ai_vendor("MIDJOURNEY") == "midjourney"

    def test_a_non_string_never_matches(self) -> None:
        assert matches_known_ai_vendor(None) is None
        assert matches_known_ai_vendor({"name": "firefly"}) is None

    def test_source_types_are_matched_exactly(self) -> None:
        """
        Ensure source types are compared exactly.

        These are controlled-vocabulary identifiers, so a near miss is a different
        claim rather than a weaker one.
        """
        assert is_ai_digital_source_type(TRAINED_ALGORITHMIC) is True
        assert is_ai_digital_source_type(TRAINED_ALGORITHMIC + "X") is False
        assert is_ai_digital_source_type(None) is False


class TestMarkerWalk:
    def test_a_buried_marker_is_found(self) -> None:
        assert contains_generative_ai_marker({"a": {"b": {"generativeAI": True}}})

    def test_an_explicit_denial_is_not_a_hit(self) -> None:
        """A marker set to false states that no AI was involved."""
        assert contains_generative_ai_marker({"generativeAI": False}) is False
        assert contains_generative_ai_marker({"generativeAI": None}) is False

    def test_the_walk_stops_at_the_depth_cap(self) -> None:
        deep: object = {"generativeAI": True}
        for _ in range(10):
            deep = {"next": deep}

        assert contains_generative_ai_marker(deep) is False

    def test_a_string_is_not_walked_as_a_sequence(self) -> None:
        assert contains_generative_ai_marker("generativeAI") is False


class TestDetectors:
    def test_the_generative_info_assertion_is_the_strongest_signal(self) -> None:
        found = detect_generative_info_assertion(
            manifest("urn:a", assertions=[{"label": "c2pa.ai.generative_info.v1"}])
        )

        assert found is not None
        assert found.confidence == 95
        assert "c2pa.ai.generative_info.v1" in found.evidence

    def test_an_ai_generated_action_fires(self) -> None:
        found = detect_ai_generated_action(
            manifest("urn:a", actions=[{"action": "c2pa.ai_generated"}])
        )

        assert found is not None and found.confidence == 95

    def test_an_algorithmic_source_type_fires(self) -> None:
        found = detect_ai_digital_source_type(
            manifest(
                "urn:a",
                actions=[
                    {"action": "c2pa.created", "digitalSourceType": TRAINED_ALGORITHMIC}
                ],
            )
        )

        assert found is not None and found.confidence == 90

    def test_a_known_agent_fires(self) -> None:
        found = detect_ai_software_agent(
            manifest(
                "urn:a",
                actions=[
                    {"action": "c2pa.created", "softwareAgent": {"name": "Midjourney"}}
                ],
            )
        )

        assert found is not None and found.confidence == 85

    def test_an_agent_named_only_in_a_description_still_fires(self) -> None:
        """
        Ensure prose descriptions are searched.

        Google's tools often set no `softwareAgent` at all and identify themselves
        only here, so this detector is the one that catches them.
        """
        found = detect_ai_action_description(
            manifest(
                "urn:a",
                actions=[
                    {
                        "action": "c2pa.created",
                        "description": "Applied imperceptible SynthID watermark.",
                    }
                ],
            )
        )

        assert found is not None and found.confidence == 80

    def test_a_metadata_marker_fires(self) -> None:
        found = detect_generative_ai_metadata_marker(
            manifest(
                "urn:a",
                assertions=[{"label": "adobe.thing", "data": {"generativeAI": True}}],
            )
        )

        assert found is not None and found.confidence == 85

    def test_a_known_claim_generator_fires(self) -> None:
        found = detect_ai_claim_generator(
            manifest("urn:a", claim_generator_info=[{"name": "OpenAI Media Service"}])
        )

        assert found is not None and found.confidence == 80

    def test_a_training_assertion_is_only_indirect(self) -> None:
        """
        Ensure the training assertion stays weak.

        It states how the asset may be *used* for training rather than how it was
        made, so on its own it must never reach the detection threshold.
        """
        found = detect_training_or_mining_assertion(
            manifest("urn:a", assertions=[{"label": "c2pa.ai.training_mining"}])
        )

        assert found is not None and found.confidence == 40

    def test_an_ordinary_edit_fires_nothing(self) -> None:
        edited = manifest(
            "urn:a",
            claim_generator="Photoshop/25.0",
            actions=[{"action": "c2pa.color_adjustments"}],
        )

        assert all(detect(edited) is None for detect in _ALL_DETECTORS)


_ALL_DETECTORS = (
    detect_generative_info_assertion,
    detect_ai_generated_action,
    detect_ai_digital_source_type,
    detect_ai_software_agent,
    detect_ai_action_description,
    detect_generative_ai_metadata_marker,
    detect_ai_claim_generator,
    detect_training_or_mining_assertion,
)


class TestVerdict:
    def test_evidence_from_an_ingredient_decides_the_verdict(self) -> None:
        """
        Ensure a generated-then-edited image is still caught.

        The active manifest records only a crop; the generation is recorded one level
        down, which is exactly the case the chain walk exists for.
        """
        store = manifest_store(
            "urn:edit",
            **{
                "urn:edit": manifest(
                    "urn:edit",
                    claim_generator="Photoshop/25.0",
                    actions=[{"action": "c2pa.cropped"}],
                    ingredients=[{"active_manifest": "urn:origin"}],
                ),
                "urn:origin": manifest(
                    "urn:origin", actions=[{"action": "c2pa.ai_generated"}]
                ),
            },
        )

        result = detect_ai_generation(get_manifest_chain(store))

        assert result.confidence == 95
        assert result.detected is True

    def test_matches_come_back_loudest_first(self) -> None:
        store = manifest_store(
            "urn:a",
            **{
                "urn:a": manifest(
                    "urn:a",
                    claim_generator="Midjourney/6",
                    actions=[
                        {
                            "action": "c2pa.ai_generated",
                            "digitalSourceType": TRAINED_ALGORITHMIC,
                        }
                    ],
                )
            },
        )

        result = detect_ai_generation(get_manifest_chain(store))

        assert [m.confidence for m in result.matches] == [95, 90, 80]

    def test_an_empty_chain_is_a_clean_zero(self) -> None:
        result = detect_ai_generation([])

        assert result.confidence == 0
        assert result.detected is False
        assert result.matches == []

    def test_every_match_names_c2pa_as_its_source(self) -> None:
        """The engine mixes layers, so each match must say where it came from."""
        store = manifest_store(
            "urn:a",
            **{"urn:a": manifest("urn:a", actions=[{"action": "c2pa.ai_generated"}])},
        )

        result = detect_ai_generation(get_manifest_chain(store))

        assert all(m.source == "c2pa" for m in result.matches)


class TestReader:
    def test_unsigned_media_reads_as_no_manifest(self) -> None:
        """
        Ensure the common case is silent.

        Most media carries no manifest at all, so this path must be an empty result
        rather than an exception.
        """
        assert read_manifest_chain(png_bytes(), "image/png") == []
        assert read_manifest_chain(jpeg_bytes(), "image/jpeg") == []

    def test_corrupt_bytes_never_raise(self) -> None:
        assert read_manifest_chain(b"not media at all", "image/jpeg") == []

    def test_an_unsupported_container_never_raises(self) -> None:
        """
        Ensure an unreadable container does not sink the whole scan.

        The metadata and model layers are independent of this one and must still get
        to report.
        """
        assert read_manifest_chain(png_bytes(), "video/quicktime") == []
