"""
Runs every provenance detector across a manifest chain.
"""

from __future__ import annotations

from typing import Iterable, List

from guard_local.detection import (
    AI_GENERATED,
    CategoryResult,
    SignalMatch,
    passes_threshold,
)

from .detectors import AI_SIGNAL_DETECTORS
from .manifest_actions import Manifest

__all__ = ["detect_ai_generation"]


def detect_ai_generation(manifests: Iterable[Manifest]) -> CategoryResult:
    """
    Evaluate a manifest chain for evidence of AI generation.

    Every detector runs against every manifest in the chain, including the ingredients
    the asset was derived from. This depth is important because an image generated by a
    model and then merely cropped records the generation in its first ingredient.
    Meanwhile, its active manifest states only that it was cropped.

    Args:
        manifests: The manifest chain exactly as returned by the reader. An
            empty chain is valid and yields an empty result.

    Returns:
        The AI generation verdict and every match found, ordered by confidence
        with the highest first.
    """
    matches: List[SignalMatch] = [
        match
        for manifest in manifests
        for detect in AI_SIGNAL_DETECTORS
        if (match := detect(manifest)) is not None
    ]
    matches.sort(key=lambda match: match.confidence, reverse=True)

    confidence = matches[0].confidence if matches else 0
    return CategoryResult(
        detected=passes_threshold(AI_GENERATED, confidence),
        confidence=confidence,
        matches=matches,
    )
